import java.math.RoundingMode
import java.text.DecimalFormat

fun main (){

    /*
    Formulate program SalesDiscount for a particular sales range generated by sale. Follow the given discount range:

    Price range                          Discount
    0 - 10,000                               0%
    10,001 - 20,000                          5%
    20,001 - 50,000                         10%
    50,001 - 100,000                        15%
    Greater than 100,000                    20%

    Sample Input/Output:
    Enter product: modem router
    Enter price : 14500.50
    Price of modem router is 14,500.50
    Discount is 725.02
    Net Price is 13,775.48
    */


    print("Enter Product name: ")
    var productName : String = readln()
    print("Enter Price: ")
    var price : Long = readln().toLong()

    //Computation for Discounts
    var zeroDiscount : Float = (price * 0 / 100).toFloat()
    var fiveDiscount : Float = (price * 5 / 100).toFloat()
    var tenDiscount : Float = (price * 10 / 100).toFloat()
    var fifteenDiscount : Float = (price * 15 / 100).toFloat()
    var twentyDiscount : Float = (price * 20 / 100).toFloat()

    //Computation for Net Price
    var zeroNetPrice : Float = (zeroDiscount - price)
    var fiveNetPrice : Float = (price - fiveDiscount)
    var tenNetPrice : Float = (price - tenDiscount)
    var fifteenNetPrice : Float = (price - fifteenDiscount)
    var twentyNetPrice : Float = (price - twentyDiscount)

    println()
    if ((price >= 0) && (price <= 10000)){
        println("Price of $productName is $price")
        println("Discount is $zeroDiscount")
        println("Net Price is $zeroNetPrice")
    }else if((price >= 10001) && (price <= 20000)){
        println("Price of $productName is $price")
        println("Discount is $fiveDiscount")
        println("Net Price is $fiveNetPrice")
    }else if((price >= 20001) && (price <= 50000)){
        println("Price of $productName is $price")
        println("Discount is $tenDiscount")
        println("Net Price is $tenNetPrice")
    }else if((price >= 50001) && (price <= 100000)){
        println("Price of $productName is $price")
        println("Discount is $fifteenDiscount")
        println("Net Price is $fifteenNetPrice")
    }else if((price >100001)){
        println("Price of $productName is $price")
        println("Discount is $twentyDiscount")
        println("Net Price is $twentyNetPrice")
    }
}