import jdk.jfr.DataAmount
import java.lang.Exception

fun main(){
    /* Practice Activity 11
    Create a kotlin program that will compute discount for a particular sales range
    generated by sale.
    Follow the given discount range:
    Price range             Discount
    0-10,000                0%
    10,001 - 20,000         5%
    20,001 - 50,000         10%
    50,001 - 100,000        15%
    Greater than 100,000    20%

    Sample Input/Output:
    Enter product: modem router
    Enter price: 14,500.50

    Price of modem router is 14,500.50
    Discount is 725.02
    Net Price is 13,775.48

    **Use Classes
    **Add error checking(Use try-catch to implement this)
    **Implement unit test (JUnit)
     */

    //Calling SalesDiscount() Class
    var salesDiscount = SalesDiscount("", 0.0.toFloat())

    var condition : Boolean = true
    while (condition){
        try{
            print("Enter Product: ")
            salesDiscount.productName = readln()
            print("Enter Price: ")
            salesDiscount.price = readln().toFloat()
            println()
            println(">Price of ${salesDiscount.productName} is ${salesDiscount.price} Pesos.")
            salesDiscount.discountAmount(salesDiscount.price)
            println()

            var condition2 : Boolean = true
            while (condition2){
                println("[?]Do you want to EXIT?[Yes/No]: ")
                var exit : String = readln().lowercase()
                if (exit == "yes"){
                    println("Program Exiting. . .")
                    condition = false
                    condition2 = false
                } else if (exit == "no"){
                    condition2 = false
                }else{
                    println("[!]Please choose between [Yes/No] only.")
                    println()
                }
            }

        }catch (e : NumberFormatException){
            println(e)
            println("[!]MESSAGE: Input Digits Only!")
            println()
        }

    }

}

class SalesDiscount(var productName: String,var price: Float){

    init{
        println("[----------------------------Welcome---------------------------]")
        println("[--------------------Product Sales Discount--------------------]")
        println()
    }

    fun discountAmount(priceToDiscount : Float){
        var totalDiscount : Float = 0.0.toFloat()
        var discountedPrice : Float = 0.0.toFloat()

        if(priceToDiscount < 1){
            println("Invalid Amount! The amount should be greater than zero(0).")

        }else if((priceToDiscount >= 0) && (priceToDiscount <= 10000)){         //0-10,000                0%
            totalDiscount = (priceToDiscount * 0 / 100).toFloat()
            discountedPrice = priceToDiscount - totalDiscount

            println(">Discount is $totalDiscount Pesos, that is 0% discount.")
            println(">Net Price is $discountedPrice Pesos")

        }else if((priceToDiscount >= 10001) && (priceToDiscount <= 20000)){     //10,001 - 20,000         5%
            totalDiscount = (priceToDiscount * 5 / 100).toFloat()
            discountedPrice = priceToDiscount - totalDiscount

            println(">Discount is $totalDiscount Pesos, that is 5% discount.")
            println(">Net Price is $discountedPrice Pesos")

        }else if((priceToDiscount >= 20001) && (priceToDiscount <= 50000)){     //20,001 - 50,000         10%
            totalDiscount = (priceToDiscount * 10 / 100).toFloat()
            discountedPrice = priceToDiscount - totalDiscount

            println(">Discount is $totalDiscount Pesos, that is 10% discount.")
            println(">Net Price is $discountedPrice Pesos")
        }
        else if((priceToDiscount >= 50001) && (priceToDiscount <= 100000)){     //50,001 - 100,000        15%
            totalDiscount = (priceToDiscount * 15 / 100).toFloat()
            discountedPrice = priceToDiscount - totalDiscount

            println(">Discount is $totalDiscount Pesos, that is 15% discount.")
            println(">Net Price is $discountedPrice Pesos")

        }else if(priceToDiscount > 100000){                                     //Greater than 100,000    20%
            totalDiscount = (priceToDiscount * 20 / 100).toFloat()
            discountedPrice = priceToDiscount - totalDiscount

            println(">Discount is $totalDiscount Pesos, that is 20% discount.")
            println(">Net Price is $discountedPrice Pesos")
        }
    }
}