import jdk.jfr.DataAmount
import java.lang.Exception

fun main(){
    /* Practice Activity 11
    Create a kotlin program that will compute discount for a particular sales range
    generated by sale.
    Follow the given discount range:
    Price range             Discount
    0-10,000                0%
    10,001 - 20,000         5%
    20,001 - 50,000         10%
    50,001 - 100,000        15%
    Greater than 100,000    20%

    Sample Input/Output:
    Enter product: modem router
    Enter price: 14,500.50

    Price of modem router is 14,500.50
    Discount is 725.02
    Net Price is 13,775.48

    **Use Classes
    **Add error checking(Use try-catch to implement this)
    **Implement unit test (JUnit)
     */

    //Calling SalesDiscount() Class
    var salesDiscount = SalesDiscount()

    var condition : Boolean = true
    while (condition){
        try{
            print("Enter Product: ")
            var productName : String = readln()
            print("Enter Price: ")
            var productPrice : Float = readln().toFloat()

            println(">Price of $productName is $productPrice Pesos.")
            salesDiscount.discountAmount(productPrice)
            println()

            var condition2 : Boolean = true
            while (condition2){
                println("[?]Do you want to EXIT?[Yes/No]: ")
                var exit : String = readln().lowercase()
                if (exit == "yes"){
                    println("Program Exiting. . .")
                    condition = false
                    condition2 = false
                } else if (exit == "no"){
                    condition2 = false
                }else{
                    println("[!]Please choose between [Yes/No] only.")
                    println()
                }
            }

        }catch (e : NumberFormatException){
            println(e)
            println("[!]MESSAGE: Input Digits Only!")
            println()
        }

    }

}

class SalesDiscount(){

    init{
        println("[----------------------------Welcome---------------------------]")
        println("[--------------------Product Sales Discount--------------------]")
        println()
    }

    fun discountAmount(price : Float): Float{
        var discount : Float = 0.0.toFloat()
        var netPrice : Float

        if(price < 1){
            println("Invalid Amount! The amount should be greater than zero(0).")

        }else if((price >= 0) && (price <= 10000)){         //0-10,000                0%
            discount = (price * 0 / 100).toFloat()
            netPrice = price - discount

            println(">Discount is $discount Pesos, that is 0% discount rate.")
            println(">Net Price is $netPrice Pesos")

        }else if((price >= 10001) && (price <= 20000)){     //10,001 - 20,000         5%
            discount = (price * 5 / 100).toFloat()
            netPrice = price - discount

            println(">Discount is $discount Pesos, that is 5% discount rate.")
            println(">Net Price is $netPrice Pesos")

        }else if((price >= 20001) && (price <= 50000)){     //20,001 - 50,000         10%
            discount = (price * 10 / 100).toFloat()
            netPrice = price - discount

            println(">Discount is $discount Pesos, that is 10% discount rate.")
            println(">Net Price is $netPrice Pesos")
        }
        else if((price >= 50001) && (price <= 100000)){     //50,001 - 100,000        15%
            discount = (price * 15 / 100).toFloat()
            netPrice = price - discount

            println(">Discount is $discount Pesos, that is 15% discount rate.")
            println(">Net Price is $netPrice Pesos")

        }else if(price > 100001){                                     //Greater than 100,000    20%
            discount = (price * 20 / 100).toFloat()
            netPrice = price - discount

            println(">Discount is $discount Pesos, that is 20% discount rate.")
            println(">Net Price is $netPrice Pesos")
        }
        return discount
    }
}